# Generated by Django 6.1 on 2026-08-14 21:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INGRESO", "Ingreso"),
                            ("GASTO", "Gasto"),
                            ("ESPECIAL_TARJETA", "Control Especial Tarjeta"),
                        ],
                        db_index=True,
                        default="GASTO",
                        max_length=20,
                        verbose_name="tipo de categoría",
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        default="folder",
                        help_text="Nombre del icono SVG/Lucide para renderizar en la interfaz.",
                        max_length=50,
                        verbose_name="icono identificador",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3BB8DB",
                        help_text="Color representativo para gráficas y etiquetas (ej: #3BB8DB).",
                        max_length=20,
                        verbose_name="código de color",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "es_fijo",
                    models.BooleanField(
                        default=False,
                        help_text="Marca si este concepto suele ser recurrente mes a mes.",
                        verbose_name="es gasto/ingreso fijo",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "ordering": ["tipo", "nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nombre", "tipo"), name="unique_nombre_tipo_categoria"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria_global",
                    models.CharField(
                        choices=[
                            ("TARJETAS", "Tarjetas de Crédito"),
                            ("COCHE", "Coche y Movilidad"),
                            ("MEDICOS", "Gastos Médicos y Salud"),
                            ("HOGAR", "Hogar y Vivienda"),
                            ("OTROS", "Otros Gastos"),
                        ],
                        db_index=True,
                        default="HOGAR",
                        help_text="Agrupación macro para reportes y comparativas de alto nivel.",
                        max_length=20,
                        verbose_name="bloque general",
                    ),
                ),
                (
                    "concepto",
                    models.CharField(max_length=255, verbose_name="concepto del gasto"),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="importe (€)",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="fecha del gasto",
                    ),
                ),
                (
                    "es_fijo",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar si es un compromiso fijo mensual (préstamo, alquiler, cuota).",
                        verbose_name="gasto fijo/recurrente",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, verbose_name="observaciones y detalles"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "GASTO"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gastos",
                        to="finanzas.categoria",
                        verbose_name="categoría detallada",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gastos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "gasto",
                "verbose_name_plural": "gastos",
                "ordering": ["-fecha", "-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="GastoEspecialTarjeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tarjeta",
                    models.CharField(
                        help_text="Nombre identificativo (ej: Visa Oro Titular 1, Mastercard Familiar).",
                        max_length=100,
                        verbose_name="tarjeta utilizada",
                    ),
                ),
                (
                    "tipo_comercio",
                    models.CharField(
                        choices=[
                            ("SUPERMERCADO", "Supermercados / Alimentación"),
                            ("MERCADO", "Mercados y Comercio Local"),
                            ("RESTAURANTE_OCIO", "Restaurantes y Ocio"),
                            ("GASOLINA", "Combustible y Estaciones de Servicio"),
                            ("COMPRAS_ONLINE", "Compras Online"),
                            ("FARMACIA_SALUD", "Farmacia y Cuidado Personal"),
                            ("OTROS", "Otros Pagos con Tarjeta"),
                        ],
                        db_index=True,
                        default="SUPERMERCADO",
                        max_length=30,
                        verbose_name="tipo de comercio",
                    ),
                ),
                (
                    "comercio",
                    models.CharField(
                        help_text="Nombre del comercio (ej: Mercadona, Carrefour, Amazon).",
                        max_length=200,
                        verbose_name="establecimiento / comercio",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="importe (€)",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="fecha de la operación",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="notas")),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "gasto_asociado",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opcional: vinculación con el apunte agregado mensual de tarjeta.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="desgloses_tarjeta",
                        to="finanzas.gasto",
                        verbose_name="gasto global vinculado",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gastos_tarjeta",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="titular / usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "control especial de tarjeta",
                "verbose_name_plural": "controles especiales de tarjetas",
                "ordering": ["-fecha", "-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Ingreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        choices=[
                            ("NOMINA_TITULAR_1", "Nómina Titular 1"),
                            ("NOMINA_TITULAR_2", "Nómina Titular 2"),
                            ("RESCATE_PLAN_PENSIONES", "Rescate Plan Pensiones"),
                            ("PENSIONES", "Pensiones"),
                            (
                                "RENDIMIENTOS_CAPITAL",
                                "Rendimientos de Capital / Inversión",
                            ),
                            ("OTROS", "Otros Ingresos"),
                        ],
                        db_index=True,
                        default="NOMINA_TITULAR_1",
                        max_length=30,
                        verbose_name="fuente de ingreso",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="importe (€)",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="fecha de percepción",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="concepto o descripción",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="observaciones")),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "INGRESO"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingresos",
                        to="finanzas.categoria",
                        verbose_name="categoría",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingresos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "ingreso",
                "verbose_name_plural": "ingresos",
                "ordering": ["-fecha", "-creado_en"],
            },
        ),
        migrations.AddIndex(
            model_name="gasto",
            index=models.Index(
                fields=["fecha", "categoria_global"],
                name="finanzas_ga_fecha_90b7bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gasto",
            index=models.Index(
                fields=["fecha", "monto"], name="finanzas_ga_fecha_7f3cd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gastoespecialtarjeta",
            index=models.Index(
                fields=["fecha", "tipo_comercio"], name="finanzas_ga_fecha_a2f6a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gastoespecialtarjeta",
            index=models.Index(
                fields=["tarjeta", "fecha"], name="finanzas_ga_tarjeta_e23450_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingreso",
            index=models.Index(
                fields=["fecha", "fuente"], name="finanzas_in_fecha_e87a2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingreso",
            index=models.Index(
                fields=["fecha", "monto"], name="finanzas_in_fecha_554be5_idx"
            ),
        ),
    ]
