# Generated by Django 6.1 on 2026-08-14 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Elemento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="nombre del elemento"
                    ),
                ),
                (
                    "es_fijo",
                    models.BooleanField(
                        default=False,
                        help_text="Marca si este elemento suele ser un compromiso recurrente mes a mes (ej: Hipoteca, Suministros).",
                        verbose_name="es gasto/ingreso fijo",
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        blank=True,
                        help_text="Icono específico opcional. Si está vacío heredará el icono de su categoría.",
                        max_length=50,
                        verbose_name="icono específico",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
            ],
            options={
                "verbose_name": "elemento",
                "verbose_name_plural": "elementos",
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.RemoveIndex(
            model_name="gasto",
            name="finanzas_ga_fecha_90b7bd_idx",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="es_fijo",
        ),
        migrations.RemoveField(
            model_name="ingreso",
            name="categoria",
        ),
        migrations.AlterField(
            model_name="categoria",
            name="icono",
            field=models.CharField(
                default="folder",
                help_text="Nombre del icono SVG/Lucide para renderizar en la interfaz (ej: home, car, heart-pulse).",
                max_length=50,
                verbose_name="icono identificador",
            ),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="concepto",
            field=models.CharField(max_length=255, verbose_name="concepto del apunte"),
        ),
        migrations.AddField(
            model_name="elemento",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elementos",
                to="finanzas.categoria",
                verbose_name="categoría",
            ),
        ),
        migrations.AddField(
            model_name="gasto",
            name="elemento",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"categoria__tipo": "GASTO"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gastos",
                to="finanzas.elemento",
                verbose_name="elemento / subcategoría",
            ),
        ),
        migrations.AddField(
            model_name="ingreso",
            name="elemento",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"categoria__tipo": "INGRESO"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingresos",
                to="finanzas.elemento",
                verbose_name="elemento / concepto",
            ),
        ),
        migrations.RemoveField(
            model_name="gasto",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="gasto",
            name="categoria_global",
        ),
        migrations.AddConstraint(
            model_name="elemento",
            constraint=models.UniqueConstraint(
                fields=("categoria", "nombre"), name="unique_elemento_por_categoria"
            ),
        ),
    ]
