# Generated by Django 6.1 on 2026-08-16 12:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finanzas",
            "0002_elemento_remove_gasto_finanzas_ga_fecha_90b7bd_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaAhorro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="nombre de la cuenta"
                    ),
                ),
                (
                    "entidad",
                    models.CharField(
                        help_text="Ej: MyInvestor, Trade Republic, Santander, Openbank, Efectivo.",
                        max_length=100,
                        verbose_name="banco / entidad",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FONDO_EMERGENCIA", "Fondo de Emergencia"),
                            ("AHORRO_OBJETIVO", "Ahorro para Objetivos / Metas"),
                            ("CUENTA_REMUNERADA", "Cuenta Remunerada / Depósito"),
                            ("INVERSION", "Inversión / Fondos Indexados"),
                            ("HUCHA_EFECTIVO", "Efectivo / Hucha"),
                            ("OTRO", "Otro Ahorro"),
                        ],
                        db_index=True,
                        default="FONDO_EMERGENCIA",
                        max_length=30,
                        verbose_name="tipo de cuenta",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3BB8DB",
                        help_text="Color distintivo para gráficas y visualización (ej: #3BB8DB).",
                        max_length=20,
                        verbose_name="código de color",
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        default="piggy-bank",
                        help_text="Nombre del icono Lucide (ej: piggy-bank, landmark, trending-up, wallet).",
                        max_length=50,
                        verbose_name="icono identificador",
                    ),
                ),
                (
                    "numero_cuenta_iban",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="IBAN o identificador (opcional)",
                    ),
                ),
                (
                    "objetivo_monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Objetivo o cantidad objetivo a alcanzar (opcional).",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="meta de ahorro (€)",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="cuenta activa"
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, verbose_name="notas / condiciones"),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cuentas_ahorro",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="titular o responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "cuenta de ahorro",
                "verbose_name_plural": "cuentas de ahorro",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="RegistroSaldoMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anio",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="año / ejercicio"
                    ),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        db_index=True, verbose_name="mes (1-12)"
                    ),
                ),
                (
                    "saldo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="saldo a fin de mes (€)",
                    ),
                ),
                (
                    "notas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="observaciones del mes"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saldos",
                        to="finanzas.cuentaahorro",
                        verbose_name="cuenta de ahorro",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de saldo mensual",
                "verbose_name_plural": "registros de saldos mensuales",
                "ordering": ["-anio", "-mes", "cuenta__nombre"],
                "indexes": [
                    models.Index(
                        fields=["anio", "mes"], name="finanzas_re_anio_819251_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cuenta", "anio", "mes"),
                        name="unique_saldo_cuenta_mes_anio",
                    )
                ],
            },
        ),
    ]
