# Generated by Django 6.1 on 2026-08-16 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0003_cuentaahorro_registrosaldomensual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ingreso",
            name="finanzas_in_fecha_e87a2a_idx",
        ),
        migrations.AlterField(
            model_name="ingreso",
            name="elemento",
            field=models.ForeignKey(
                limit_choices_to={"categoria__tipo": "INGRESO"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingresos",
                to="finanzas.elemento",
                verbose_name="elemento / concepto de ingreso",
            ),
        ),
        migrations.AddIndex(
            model_name="ingreso",
            index=models.Index(
                fields=["elemento", "fecha"], name="finanzas_in_element_c548bb_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="ingreso",
            name="fuente",
        ),
    ]
