# Generated by Django 6.1 on 2026-08-17 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0004_remove_ingreso_finanzas_in_fecha_e87a2a_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="gastoespecialtarjeta",
            name="finanzas_ga_fecha_a2f6a4_idx",
        ),
        migrations.RemoveIndex(
            model_name="gastoespecialtarjeta",
            name="finanzas_ga_tarjeta_e23450_idx",
        ),
        migrations.AlterField(
            model_name="categoria",
            name="color",
            field=models.CharField(
                default="#3BB8DB",
                help_text="Color representativo para gráficas y etiquetas (ej: #3BB8DB).",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Introduce un color en formato hexadecimal (ej: #3BB8DB).",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$",
                    )
                ],
                verbose_name="código de color",
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="icono",
            field=models.CharField(
                default="folder",
                help_text="Nombre del icono SVG/Lucide para renderizar en la interfaz (ej: home, car, heart-pulse).",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El icono solo puede contener letras, números, guiones y subrayados.",
                        regex="^[a-zA-Z0-9][a-zA-Z0-9_-]*$",
                    )
                ],
                verbose_name="icono identificador",
            ),
        ),
        migrations.AlterField(
            model_name="cuentaahorro",
            name="color",
            field=models.CharField(
                default="#3BB8DB",
                help_text="Color distintivo para gráficas y visualización (ej: #3BB8DB).",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Introduce un color en formato hexadecimal (ej: #3BB8DB).",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$",
                    )
                ],
                verbose_name="código de color",
            ),
        ),
        migrations.AlterField(
            model_name="cuentaahorro",
            name="icono",
            field=models.CharField(
                default="piggy-bank",
                help_text="Nombre del icono Lucide (ej: piggy-bank, landmark, trending-up, wallet).",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El icono solo puede contener letras, números, guiones y subrayados.",
                        regex="^[a-zA-Z0-9][a-zA-Z0-9_-]*$",
                    )
                ],
                verbose_name="icono identificador",
            ),
        ),
        migrations.AlterField(
            model_name="elemento",
            name="icono",
            field=models.CharField(
                blank=True,
                help_text="Icono específico opcional. Si está vacío heredará el icono de su categoría.",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El icono solo puede contener letras, números, guiones y subrayados.",
                        regex="^[a-zA-Z0-9][a-zA-Z0-9_-]*$",
                    )
                ],
                verbose_name="icono específico",
            ),
        ),
        migrations.DeleteModel(
            name="GastoEspecialTarjeta",
        ),
    ]
