# Generated by Django 6.1 on 2026-08-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finanzas",
            "0005_remove_gastoespecialtarjeta_finanzas_ga_fecha_a2f6a4_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="elemento",
            name="fecha_finalizacion",
            field=models.DateField(
                blank=True,
                help_text="Fecha en la que se terminó de pagar (opcional).",
                null=True,
                verbose_name="fecha de finalización",
            ),
        ),
        migrations.AddField(
            model_name="elemento",
            name="finalizado",
            field=models.BooleanField(
                default=False,
                help_text="Marca cuando este compromiso se ha terminado de pagar (ej: hipoteca liquidada).",
                verbose_name="finalizado / pagado",
            ),
        ),
    ]
