# Generated by Django 6.1 on 2026-10-05 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_prestamos_reparentar_hipoteca_renting_coche'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='medio_pago',
            field=models.CharField(choices=[('DOMICILIADO', 'Domiciliado / Cargo en cuenta'), ('TARJETA', 'Pagado con Tarjeta (desglose)'), ('LIQUIDACION_TARJETA', 'Liquidación mensual de Tarjeta'), ('EFECTIVO', 'Efectivo')], db_index=True, default='DOMICILIADO', help_text='Indica si es cargo domiciliado en cuenta, compra pagada con tarjeta (desglose que no duplica) o la liquidación global de la tarjeta.', max_length=25, verbose_name='medio de pago'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['medio_pago', 'fecha'], name='finanzas_ga_medio_p_b4d129_idx'),
        ),
    ]
