# Generated by Django 6.1 on 2026-10-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_gasto_medio_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('DOMICILIADO', 'Domiciliado / Cargo en cuenta'), ('TARJETA', 'Pagado con Tarjeta (desglose)'), ('LIQUIDACION_TARJETA', 'Liquidación mensual de Tarjeta'), ('EFECTIVO', 'Efectivo')], default='DOMICILIADO', help_text='Forma de pago por defecto para este concepto (se aplicará automáticamente al registrar un gasto).', max_length=25, verbose_name='medio de pago habitual'),
        ),
    ]
