# Generated by Django 6.1 on 2026-08-14 21:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Seguro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ramo",
                    models.CharField(
                        choices=[
                            ("HOGAR", "Hogar / Vivienda"),
                            ("COCHE", "Vehículo / Coche / Moto"),
                            ("SALUD", "Salud y Asistencia Médica"),
                            ("VIDA", "Vida y Accidentes"),
                            ("DECESOS", "Decesos"),
                            ("RESPONSABILIDAD_CIVIL", "Responsabilidad Civil"),
                            ("MASCOTAS", "Mascotas"),
                            ("OTROS", "Otros Seguros"),
                        ],
                        db_index=True,
                        default="HOGAR",
                        max_length=30,
                        verbose_name="tipo / ramo de seguro",
                    ),
                ),
                (
                    "compania",
                    models.CharField(
                        help_text="Nombre de la aseguradora (ej: Mapfre, Allianz, Mutua Madrileña, Axa).",
                        max_length=150,
                        verbose_name="compañía aseguradora",
                    ),
                ),
                (
                    "numero_poliza",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="número de póliza"
                    ),
                ),
                (
                    "bien_asegurado",
                    models.CharField(
                        help_text="Descripción breve (ej: Vivienda principal, Seat León 1234-XYZ, Familia García).",
                        max_length=200,
                        verbose_name="bien o personas aseguradas",
                    ),
                ),
                (
                    "gestor_nombre",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="nombre del mediador / gestor",
                    ),
                ),
                (
                    "gestor_telefono",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="teléfono del gestor"
                    ),
                ),
                (
                    "gestor_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="correo electrónico del gestor",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de efecto / inicio"
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        db_index=True,
                        help_text="Fecha clave para preaviso y renegociación de la prima.",
                        verbose_name="fecha de vencimiento / renovación",
                    ),
                ),
                (
                    "periodicidad",
                    models.CharField(
                        choices=[
                            ("ANUAL", "Anual"),
                            ("SEMESTRAL", "Semestral"),
                            ("TRIMESTRAL", "Trimestral"),
                            ("MENSUAL", "Mensual"),
                        ],
                        default="ANUAL",
                        max_length=20,
                        verbose_name="periodicidad del pago",
                    ),
                ),
                (
                    "prima_actual",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Coste total anualizado o de la última renovación.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="prima actual (€)",
                    ),
                ),
                (
                    "prima_anterior",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coste del año previo para el cálculo comparativo.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="prima periodo anterior (€)",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="póliza en vigor"
                    ),
                ),
                (
                    "notas_negociacion",
                    models.TextField(
                        blank=True,
                        help_text="Estrategia de negociación con el gestor, contraofertas y condiciones clave.",
                        verbose_name="notas de negociación / coberturas",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seguros",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="titular o responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "seguro",
                "verbose_name_plural": "seguros",
                "ordering": ["fecha_vencimiento", "compania"],
            },
        ),
        migrations.CreateModel(
            name="HistorialRenovacionSeguro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ejercicio_anio",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="año / ejercicio"
                    ),
                ),
                (
                    "prima_pagada",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="prima pagada (€)",
                    ),
                ),
                (
                    "fecha_renovacion",
                    models.DateField(verbose_name="fecha de cobro / renovación"),
                ),
                (
                    "notas",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="observaciones"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "seguro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="seguros.seguro",
                        verbose_name="póliza vinculada",
                    ),
                ),
            ],
            options={
                "verbose_name": "historial de renovación de seguro",
                "verbose_name_plural": "historiales de renovación de seguros",
                "ordering": ["-ejercicio_anio"],
            },
        ),
        migrations.AddIndex(
            model_name="seguro",
            index=models.Index(
                fields=["activo", "fecha_vencimiento"],
                name="seguros_seg_activo_04ee8a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="historialrenovacionseguro",
            constraint=models.UniqueConstraint(
                fields=("seguro", "ejercicio_anio"), name="unique_seguro_ejercicio"
            ),
        ),
    ]
