# Generated by Django 6.1 on 2026-08-16 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finanzas",
            "0002_elemento_remove_gasto_finanzas_ga_fecha_90b7bd_idx_and_more",
        ),
        ("seguros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seguro",
            name="elemento",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seguro",
                to="finanzas.elemento",
                verbose_name="elemento contable vinculado",
            ),
        ),
    ]
