import os
from dotenv import load_dotenv

load_dotenv()

"""
Django settings for contabilidad project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

raw_hosts = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in raw_hosts.split(",") if h.strip()]
if not ALLOWED_HOSTS and DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "::1"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Local apps
    "usuarios.apps.UsuariosConfig",
    "finanzas.apps.FinanzasConfig",
    "seguros.apps.SegurosConfig",
]

AUTH_USER_MODEL = "usuarios.Usuario"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "contabilidad.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.debug",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "contabilidad.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("DB_NAME", "contabilidad"),
        "USER": os.getenv("DB_USER", "kike"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "es-es"

TIME_ZONE = "Europe/Madrid"

USE_I18N = True

USE_TZ = True

# Formatos de fecha en español (dd/mm/yyyy)
DATE_FORMAT = "d/m/Y"
DATE_INPUT_FORMATS = [
    "%d/%m/%Y",  # 25/12/2026
    "%d/%m/%y",  # 25/12/26
    "%d-%m-%Y",  # 25-12-2026
    "%d-%m-%y",  # 25-12-26
    "%Y-%m-%d",  # 2026-12-25 (formato ISO para compatibilidad interna y tests)
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# Auth redirects
LOGIN_URL = "usuarios:login"
LOGIN_REDIRECT_URL = "finanzas:dashboard"
LOGOUT_REDIRECT_URL = "usuarios:login"


# ==============================================================================
# CONFIGURACIÓN DE SEGURIDAD Y SSL / HTTPS (ENTORNO DE PRODUCCIÓN)
# ==============================================================================
# NOTA PARA DESARROLLO:
# Dado que en el servidor de desarrollo no se usan certificados SSL, el siguiente
# bloque se mantiene comentado. Si se activara en desarrollo sobre HTTP plano,
# el navegador sufriría bucles de redirección a https:// y las cookies de sesión/CSRF
# serían rechazadas.
#
# Para activar en el servidor de PRODUCCIÓN (cuando existan certificados SSL válidos),
# descomentar las siguientes directivas:
#
# if not DEBUG:
#     # Redirige automáticamente todas las peticiones HTTP a HTTPS (puerto 443).
#     # Evita que el tráfico sensible viaje sin cifrar por la red.
#     SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True") == "True"
#
#     # Marca la cookie de sesión con el atributo 'Secure'. El navegador solo la
#     # enviará si la conexión es HTTPS, evitando robo de sesión (Session Hijacking).
#     SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "True") == "True"
#
#     # Marca la cookie de protección contra CSRF con el atributo 'Secure'.
#     # Garantiza que el token CSRF viaje exclusivamente cifrado.
#     CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "True") == "True"
#
#     # HTTP Strict Transport Security (HSTS): Instruye a los navegadores a recordar
#     # que este dominio debe visitarse SIEMPRE mediante HTTPS durante el tiempo indicado
#     # (31536000 segundos = 1 año), previniendo ataques Man-in-the-Middle y SSL-strip.
#     SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS", "True") == "True"
#     SECURE_HSTS_PRELOAD = os.getenv("SECURE_HSTS_PRELOAD", "True") == "True"
#
#     # Indica a Django que confíe en la cabecera 'X-Forwarded-Proto: https' enviada por
#     # un proxy inverso (Nginx, Caddy, Cloudflare, Traefik).
#     # ¡ATENCIÓN!: Únicamente activar si el proxy inverso está configurado para sanear
#     # y eliminar esta cabecera si proviene directamente de clientes no confiables.
#     SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Directivas de seguridad recomendadas (compatibles tanto con HTTP como con HTTPS):
SECURE_CONTENT_TYPE_NOSNIFF = True   # Previene ataques basados en adivinación de tipo MIME (MIME-sniffing)
X_FRAME_OPTIONS = "DENY"             # Protege contra Clickjacking impidiendo incrustar el sitio en iframes
SECURE_REFERRER_POLICY = "same-origin"  # No filtra URLs internas completas a dominios externos en Referer


